routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Middleware\Authenticate;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\HomeController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\ProductOptionController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductCategoryController;
use App\Http\Controllers\ImageStoreController;
use App\Http\Controllers\EshopController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\SettingsController;


Route::get('/', [HomeController::class, 'Index'])->name('home');

Route::get('login', [AuthController::class, 'Login'])->name('login');
Route::get('logout', [AuthController::class, 'Logout']);
Route::post('login', [AuthController::class, 'LoginPost']);

Route::prefix('eshop')->group(function(){
	Route::get('/', [EshopController::class, 'index'])->name('eshop');
	Route::get('detail/{id}', [EshopController::class, 'detail'])->name('detail');
	Route::post('get_options', [EshopController::class, 'get_options_for_parent'])->name('get_options');
	Route::get('checkout', [EshopController::class, 'checkout'])->name('checkout');
	Route::post('checkout', [EshopController::class, 'checkout_post'])->name('checkout');

	Route::prefix('cart')->group(function()
	{
		Route::post('show', [CartController::class, 'cart'])->name('show_cart');
		Route::post('add_to_cart', [CartController::class, 'add_to_cart'])->name('add_to_cart');
		Route::post('remove_from_cart', [CartController::class, 'remove_from_cart'])->name('remove_from_cart');
		Route::post('adjust_count', [CartController::class, 'adjust_cart_product_count'])->name('adjust_count');
	});
});





Route::prefix('test')->group(function(){
	Route::get('cart',  function(){
		 return view('public._partials.cart', ['cart' => session()->get('cart')]);
	});
	Route::get('test', function(){
		$cart = session()->get('cart');
		var_dump(\App\Lib\Cart::getProductCount()  );
		var_dump($cart);
		var_dump($cart['products'][1]['options']);
		$cart = [];
		// session()->put('cart', $cart);
	});

	Route::get('mail', function(){

		$to_name = 'Tomas';
		$to_email = 'r.vrecnik@gmail.com';
		$data = array('name'=>"Ogbonna Vitalis", "body" => "A test mail");
		// Mail::send("emails.mail", $data, function($message) use ($to_name, $to_email) {$message->to($to_email, $to_name)->subject('Laravel Test Mail');$message->from('wrecko@centrum.sk','Test Mail');
		// });

		Mail::to($to_email)->send(new App\Mail\OrderCreated(new App\Models\Order()));
	});

			

	
});



Route::middleware([Authenticate::class])->group(function (){

	Route::get('admin', [AdminController::class, 'Index']);
	Route::prefix('admin')->group(function()
	{
		Route::get('product_option', [ProductOptionController::class, 'ProductOption'])->name('options');

		Route::post('optionCreate', [ProductOptionController::class, 'OptionCreate'])->name('option_create');	
		Route::post('optionUpdate', [ProductOptionController::class, 'OptionUpdate'])->name('option_update');
		Route::get('optionDelete/{id}', [ProductOptionController::class, 'POptionDelete'])->name('option_delete');

		Route::post('optionTypeCreate', [ProductOptionController::class, 'OptionTypeCreate'])->name('option_type_create');	
		Route::post('optionTypeUpdate', [ProductOptionController::class, 'OptionTypeUpdate'])->name('option_type_update');	
		Route::get('optionTypeDelete/{id}', [ProductOptionController::class, 'OptionTypeDelete'])->name('option_type_delete');

		Route::post('optionRelationCreate', [ProductOptionController::class, 'OptionRelationCreate'])->name('option_relation_create');	
		Route::post('optionRelationUpdate', [ProductOptionController::class, 'OptionRelationUpdate'])->name('option_relation_update');	
		Route::get('optionRelationDelete/{id}', [ProductOptionController::class, 'OptionRelationDelete'])->name('option_relation_delete');	

		Route::get('category', [ProductCategoryController::class, 'index'])->name('categories');
		Route::post('categoryCreate', [ProductCategoryController::class, 'create'])->name('category_create');
		Route::post('categoryUpdate', [ProductCategoryController::class, 'update'])->name('category_update');
		Route::get('categoryDelete/{id}', [ProductCategoryController::class, 'delete'])->name('category_delete');

		Route::get('product', [ProductController::class, 'index'])->name('products');		
		Route::prefix('product')->group(function(){
				Route::get('create', [ProductController::class, 'create'])->name('product_create');
				Route::post('create', [ProductController::class, 'createpost'])->name('product_create');	
				Route::post('save_images', [ImageStoreController::class, 'storeimages'])->name('save_images');		
				Route::post('delete_images', [ImageStoreController::class, 'deleteimages'])->name('delete_image');	
				Route::post('add_options_list', [ProductController::class, 'addoptionslist'])->name('add_options_list');	


				Route::get('edit/{id}', [ProductController::class, 'update'])->name('product_edit');
				Route::post('edit', [ProductController::class, 'updatepost'])->name('product_edit');
				Route::get('delete/{id}', [ProductController::class, 'delete'])->name('product_delete');
		});

		Route::prefix('order')->group(function(){
			Route::get('/', [OrderController::class, 'index'])->name('orders');
			Route::get('/{id}', [OrderController::class, 'detail'])->name('order_detail');
			//	TODO maybe change to post???
			Route::get('change_status/{id}/{status}', [OrderController::class, 'change_status'])->name('change_status');
		});

		Route::get('settings', [SettingsController::class, 'index'])->name('settings');	
		Route::prefix('settings')->group(function(){
			Route::post('save_fees', [SettingsController::class, 'save_fees'])->name('save_fees');	

		});
		
	});
});

app/Http/Controllers/SettingsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Transport;
use App\Models\TransportFee;

class SettingsController extends Controller
{
    public function index()
    {
    	return view('admin.settings.index',
    		[
    			'transports'	=> Transport::withCount('fees')->get()
    		]
    	);
    }

    public function save_fees(Request $request)
    {
    	
    	try
    	{
    		foreach ($request->all()['fees'] as $key => $value) 
    		{    
	    		TransportFee::where('id', $key)->update([
	    			'free_of_charge'	=> isset($value['free_of_charge'])? 1 : 0,
	    			'price' 			=> isset($value['price'])? $value['price'] : 0
	    		]);
    		}
    	}
    	catch (\Exception $e) {
            var_dump($e);
            return;
        }

    	return redirect()->back();
    }
}

resources/views/admin/Settings/index.blade.php
@extends('admin._layout')

@section('content')

<div class="header-text">
	<h2>Settings</h2>
	<input type="button" id="save_fee_btn" class="btn btn-success top-submit-btn" value="SAVE">
</div>
<hr>

<div class="weight-transport-section">
	<h3> Transport fees </h3>
	<hr>

	<form action="{{ route('save_fees') }}" method="post", id="fees-form">  
	@csrf()
		<div class="fee-table">
			
			@foreach($transports as $transport)			
				@if($transport->fees_count == 0)
					@continue
				@endif
				<div id="transport-{{$transport->id}}">
					<span class="transport-name">{{$transport->name}}</span>

					<table class="table">
					 <thead>
				        <tr>		            
				            <!-- <th scope="col">From (g)</th>
				            <th scope="col">To (g)</th> -->
				            <th scope="col">State name</th>
				            <th scope="col">Price</th>
				            <th scope="col">Free of charge</th>
				        </tr>
				    </thead>
			    	<tbody>   
			    		@foreach($transport->fees as $fee)
			    			<tr>
			    				<!-- <td>
			    					<input type="text" class="form-control" name="fees[{{$transport->id}}][from_weight]" value="{{$fee->from_weight}}" 
			    					@if($fee->free_of_charge)
					                    disabled
					                @endif>
			    				</td>
			    				<td>
			    					<input type="text" class="form-control" name="fees[{{$transport->id}}][to_weight]" value="{{$fee->to_weight}}"
			    					@if($fee->free_of_charge)
					                    disabled
					                @endif>
			    				</td> -->
			    				<td>
			    					<span>{{$fee->state_name}}</span>
			    				</td>
			    				<td>
			    					<input type="text" class="form-control" name="fees[{{$fee->id}}][price]" value="{{$fee->price}}"
			    					@if($fee->free_of_charge)
					                    disabled
					                @endif>
			    				</td>
			    				<td>
			    					<input type="checkbox" class="free_of_charge_check" name="fees[{{$fee->id}}][free_of_charge]"
					                @if($fee->free_of_charge)
					                    checked
					                @endif>
			    					<!-- <input type="hidden" name="fees[{{$transport->id}}][id]" value="{{$fee->id}}"> -->
			    				</td>
			    			</tr>
			    		@endforeach
			    	</tbody>
				</table>
				</div>
			
			@endforeach
			
		</div>

		<div class="add-fee">
			<div class="row">
				<!-- <div class="col-md-6">
					<select class="form-control">
						@foreach($transports as $trans)
							<option value="{{$trans->id}}">{{$trans->name}}</option>
						@endforeach
					</select>
				</div> -->
				<div class="col-md-6">
					<!-- <input type="button" class="btn btn-success" value="ADD"> -->					
				</div>
				
			</div>
		</div>
	</form>
</div>


@endsection

@section('BottomScripts')
<script type="text/javascript">
	$('.free_of_charge_check').change(function(){
		var inputs = $(this).parents('tr').find('input:text');
		if(this.checked) 
		{
			$.each(inputs, function(i,val){
				 $(val).prop("disabled", true);
			})
		}
		else
		{
			$.each(inputs, function(i,val){
				 $(val).prop("disabled", false);
			})
		}
		
	})	



</script>
@endsection