routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Middleware\Authenticate;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\HomeController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\ProductOptionController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductCategoryController;
use App\Http\Controllers\ImageStoreController;
use App\Http\Controllers\EshopController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\SettingsController;


Route::get('/', [HomeController::class, 'Index'])->name('home');

Route::get('login', [AuthController::class, 'Login'])->name('login');
Route::get('logout', [AuthController::class, 'Logout']);
Route::post('login', [AuthController::class, 'LoginPost']);

Route::prefix('eshop')->group(function(){
	Route::get('/', [EshopController::class, 'index'])->name('eshop');
	Route::get('detail/{id}', [EshopController::class, 'detail'])->name('detail');
	Route::post('get_options', [EshopController::class, 'get_options_for_parent'])->name('get_options');
	Route::get('checkout', [EshopController::class, 'checkout'])->name('checkout');
	Route::post('checkout', [EshopController::class, 'checkout_post'])->name('checkout');

	Route::prefix('cart')->group(function()
	{
		Route::post('show', [CartController::class, 'cart'])->name('show_cart');
		Route::post('add_to_cart', [CartController::class, 'add_to_cart'])->name('add_to_cart');
		Route::post('remove_from_cart', [CartController::class, 'remove_from_cart'])->name('remove_from_cart');
		Route::post('adjust_count', [CartController::class, 'adjust_cart_product_count'])->name('adjust_count');
	});
});





Route::prefix('test')->group(function(){
	Route::get('cart',  function(){
		 return view('public._partials.cart', ['cart' => session()->get('cart')]);
	});
	Route::get('test', function(){
		$cart = session()->get('cart');
		var_dump(\App\Lib\Cart::getProductCount()  );
		var_dump($cart);
		var_dump($cart['products'][1]['options']);
		$cart = [];
		// session()->put('cart', $cart);
	});

	Route::get('mail', function(){

		$to_name = 'Tomas';
		$to_email = 'r.vrecnik@gmail.com';
		$data = array('name'=>"Ogbonna Vitalis", "body" => "A test mail");
		// Mail::send("emails.mail", $data, function($message) use ($to_name, $to_email) {$message->to($to_email, $to_name)->subject('Laravel Test Mail');$message->from('wrecko@centrum.sk','Test Mail');
		// });

		Mail::to($to_email)->send(new App\Mail\OrderCreated(new App\Models\Order()));
	});

			

	
});



Route::middleware([Authenticate::class])->group(function (){

	Route::get('admin', [AdminController::class, 'Index']);
	Route::prefix('admin')->group(function()
	{
		Route::get('product_option', [ProductOptionController::class, 'ProductOption'])->name('options');

		Route::post('optionCreate', [ProductOptionController::class, 'OptionCreate'])->name('option_create');	
		Route::post('optionUpdate', [ProductOptionController::class, 'OptionUpdate'])->name('option_update');
		Route::get('optionDelete/{id}', [ProductOptionController::class, 'POptionDelete'])->name('option_delete');

		Route::post('optionTypeCreate', [ProductOptionController::class, 'OptionTypeCreate'])->name('option_type_create');	
		Route::post('optionTypeUpdate', [ProductOptionController::class, 'OptionTypeUpdate'])->name('option_type_update');	
		Route::get('optionTypeDelete/{id}', [ProductOptionController::class, 'OptionTypeDelete'])->name('option_type_delete');

		Route::post('optionRelationCreate', [ProductOptionController::class, 'OptionRelationCreate'])->name('option_relation_create');	
		Route::post('optionRelationUpdate', [ProductOptionController::class, 'OptionRelationUpdate'])->name('option_relation_update');	
		Route::get('optionRelationDelete/{id}', [ProductOptionController::class, 'OptionRelationDelete'])->name('option_relation_delete');	

		Route::get('category', [ProductCategoryController::class, 'index'])->name('categories');
		Route::post('categoryCreate', [ProductCategoryController::class, 'create'])->name('category_create');
		Route::post('categoryUpdate', [ProductCategoryController::class, 'update'])->name('category_update');
		Route::get('categoryDelete/{id}', [ProductCategoryController::class, 'delete'])->name('category_delete');

		Route::get('product', [ProductController::class, 'index'])->name('products');		
		Route::prefix('product')->group(function(){
				Route::get('create', [ProductController::class, 'create'])->name('product_create');
				Route::post('create', [ProductController::class, 'createpost'])->name('product_create');	
				Route::post('save_images', [ImageStoreController::class, 'storeimages'])->name('save_images');		
				Route::post('delete_images', [ImageStoreController::class, 'deleteimages'])->name('delete_image');	
				Route::post('add_options_list', [ProductController::class, 'addoptionslist'])->name('add_options_list');	


				Route::get('edit/{id}', [ProductController::class, 'update'])->name('product_edit');
				Route::post('edit', [ProductController::class, 'updatepost'])->name('product_edit');
				Route::get('delete/{id}', [ProductController::class, 'delete'])->name('product_delete');
		});

		Route::prefix('order')->group(function(){
			Route::get('/', [OrderController::class, 'index'])->name('orders');
			Route::get('/{id}', [OrderController::class, 'detail'])->name('order_detail');
			//	TODO maybe change to post???
			Route::get('change_status/{id}/{status}', [OrderController::class, 'change_status'])->name('change_status');
		});

		Route::get('settings', [SettingsController::class, 'index'])->name('settings');	
		Route::prefix('settings')->group(function(){
			Route::post('save_fees', [SettingsController::class, 'save_fees'])->name('save_fees');	

		});
		
	});
});

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Enums\OrderStatus;


class Order extends Model
{
    use HasFactory;

 	protected $table = 'order';
    protected $fillable = ['name', 'surname', 'street', 'zip', 'city', 'state', 'email', 'phone_number', 'note', 'total_price', 'total_price_vat', 'payment', 'transport', 'order_status'];

    protected $state;

    // protected $maps = [ 'state' => 'state_id'];
    protected $append = ['state_id'];
    

    public function state()
    {
    	return $this->belongsTo('App\Models\State', 'state_id', 'id');
    }
    public function order_products()
    {
    	return $this->hasMany('App\Models\OrderProduct', 'order_id', 'id');
    }

    public function getFullNameAttribute()
    {
        return ucfirst($this->name) . ' ' . ucfirst($this->surname);
    }

    public function getFullAddressAttribute()
    {
        return "{$this->street}, {$this->zip} {$this->city}";
    }

    public function getOrderStatusNameAttribute()
    {        
        return OrderStatus::toString($this->order_status);
    }

    public function getOrderStatusClassAttribute()
    {       
        
        switch ($this->order_status)
        {
            case OrderStatus::NEW: return "btn-secondary";
            case OrderStatus::ACCEPTED: return "btn-success"; 
            case OrderStatus::EXPEDITED: return  "btn-warning"; 
            case OrderStatus::CLOSED: return  "btn-info"; 
            case OrderStatus::INVALID: return "btn-danger"; 
            default:
                return "btn-secondary";
        }
    }

    //  TODO: 
    // public function getPhoneNumberWithPrefixAttribute()
    // {   
    //     return "+{$this->state()->get()->phone_prefix} {$this->phone_number}";
    // }

    public static function boot()
    {
        parent::boot();

        self::creating(function($model){
            $model->attributes['state_id'] = $model->attributes['state'];
            unset($model->attributes['state']);
        });
    }
}

app/Models/ProductImage.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ProductImage extends Model
{
    use HasFactory;

    protected $table = 'product_image';
    protected $fillable = ['product_id', 'name', 'is_thumbnail', 'session_id'];

    public function getPathAttribute()
    {
        return asset(config('global.IMAGE_UPLOAD_PATH') . $this->product_id . '\\' .$this->name);
    }

    public function get_image_path()
    {
    	// return public_path() . '\\' . config('global.IMAGE_UPLOAD_PATH') .$this->product_id . '\\' .$this->name;
    	return asset(config('global.IMAGE_UPLOAD_PATH') . $this->product_id . '\\' .$this->name);
    }

    public function get_image_absolute_path()
    {
    	return public_path() . '\\' . config('global.IMAGE_UPLOAD_PATH') .$this->product_id . '\\' .$this->name;
    }

    public function delete_with_files()
    {        
        try 
        {
            $this->delete();
            unlink($this->get_image_absolute_path());
        } 
        catch (Exception $e) 
        {
            // TODO: audit exception
            echo 'Caught exception: ',  $e->getMessage(), "\n";
        }
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Order;

class OrderController extends Controller
{
    public function index()
    {
    	return view('admin.order.index', [
    		'orders'	=> Order::all()
    	]);
    }

    public function detail($id)
    {
    	// var_dump($id, Order::findorfail($id)->with('order_products')->get());
    	return view('admin.order.detail', [
    		'order'	=> Order::findorfail($id)
    	]);
    }

    public function change_status($id, $status)
    {
        // var_dump($id, $status);

        if(Order::where('id', $id)->update(['order_status'=> $status]))
        {
            return redirect()->back();
        }
        
    }
}

resources/views/admin/Order/detail.blade.php
@extends('admin._layout')

@section('content')



<h1>Order #{{$order->id}}</h1>
<hr />
<div class="admin-order-detail">
    <div class="order-customer">
        <h3>Customer</h3>
        <hr />
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="fullname" class="">Full name:</label>
                    <input type="text" value="{{$order->full_name}}" class="form-control" disabled />
                </div>
                <div class="form-group">
                    <label for="fullname" class="">Address:</label>
                    <input type="text" value="{{$order->full_address}}, {{$order->state->name}}" class="form-control" disabled />
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="fullname" class="">Phone number:</label>
                    <input type="text" value="+{{$order->state->phone_prefix}} {{$order->phone_number}}" class="form-control" disabled />
                </div>
                <div class="form-group">
                    <label for="fullname" class="">Email address:</label>
                    <input type="text" value="{{$order->email}}" class="form-control" disabled />
                </div>
            </div>
        </div>        
    </div>
    <div class="order-detail">
        <div class="row">
            <div class="col">
                <h3>Products</h3>
                <hr />
                <div class="order-products">
                    @foreach($order->order_products as $prod)
                    
                        <div class="prod">
                            <div class="prod-img">
                                <img src="{{$prod->product->images->first()->path}}" alt="{{$prod->product->name}}" />
                            </div>
                            <div class="prod-detail">
                                <span>{{$prod->product->name}}</span>
                                <br />
                                <span><!-- prod.ParentOptionName prod.OptionName --></span>
                                <span>{{$prod->count}} pcs.</span>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
            <div class="col">
                <h3>Details</h3>
                <hr />
                <div class="price-total">
                    <span class="hdr">Price Total: </span>                    
                    <span style="font-size: 18px;">{{$order->total_price_vat}}&euro; ({{$order->total_price}}&euro; w/o VAT)</span>
                </div>

                <div class="order-status m-t-10">
                    <span class="hdr">Order status:</span>
                    <span style="font-weight: 600; text-transform: uppercase;">{{$order->order_status_name}}</span>
                    <br />
                    <br />
                    <span class="hdr">Change status to:</span>
                    <div class="row m-t-10" style="text-transform: uppercase;">
                        <div class="col">
                            <a href="{{route('change_status', ['id' => $order->id, 'status' => App\Enums\OrderStatus::ACCEPTED])}}" class="btn btn-success">{{App\Enums\OrderStatus::toString(App\Enums\OrderStatus::ACCEPTED)}}</a>
                            
                        </div>
                        <div class="col">
                            <a href="{{route('change_status', ['id' => $order->id, 'status' => App\Enums\OrderStatus::EXPEDITED])}}" class="btn btn-warning">{{App\Enums\OrderStatus::toString(App\Enums\OrderStatus::EXPEDITED)}}</a>
                           
                        </div>
                        <div class="col">
                            <a href="{{route('change_status', ['id' => $order->id, 'status' => App\Enums\OrderStatus::CLOSED])}}" class="btn btn-info">{{App\Enums\OrderStatus::toString(App\Enums\OrderStatus::CLOSED)}}</a>
                           
                        </div>
                        <div class="col">
                            <a href="{{route('change_status', ['id' => $order->id, 'status' => App\Enums\OrderStatus::INVALID])}}" class="btn btn-danger">{{App\Enums\OrderStatus::toString(App\Enums\OrderStatus::INVALID)}}</a>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
</div>

@endsection

resources/views/admin/Order/index.blade.php
@extends('admin._layout')

@section('content')


<div class="admin-category-add">
    <h2>Orders</h2>
    <input type="text" placeholder="Search..." class="form-control mx-sm-3" id="search" />
</div>

<table class="table table-striped table-dark">
    <thead>
        <tr>
            <th scope="col">Order #</th>
            <th scope="col">Name</th>
            <th scope="col">Address</th>
            <th scope="col">Price(VAT)</th>
            <th scope="col">Order Status</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        
        @foreach($orders as $order)
        
            <tr>
                <td>{{$order->id}}</td>
                <td>{{$order->full_name}}</td>
                <td>{{$order->full_address}}</td>
                <td>{{$order->total_price_vat}}&euro;</td>
                <td>
                    <span class="btn {{$order->order_status_class}}" style="cursor: default;">{{$order->order_status_name}}</span>
                </td>
                <td style="text-align:center;">
                    <a href="{{route('order_detail',['id' => $order->id])}}" class="btn btn-warning">DETAIL</a>
                    
                </td>
            </tr>
        @endforeach

        

    </tbody>
</table>

@endsection